export const COLLATERAL_SMART_CONTRACT_ADDRESS =
  '0xa932baCD45512afE81981b8fc2E243448AD19d9c' as const;

export const COLLATERAL_SMART_CONTRACT_ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  {
    inputs: [],
    name: 'CollateralRegistry__AgreementAlreadyExists',
    type: 'error',
  },
  {
    inputs: [],
    name: 'CollateralRegistry__AgreementDoesNotExist',
    type: 'error',
  },
  {
    inputs: [],
    name: 'CollateralRegistry__CollateralRentalDoesNotSupportNFTType',
    type: 'error',
  },
  { inputs: [], name: 'CollateralRegistry__DeadlinePassed', type: 'error' },
  {
    inputs: [],
    name: 'CollateralRegistry__InvalidDealDuration',
    type: 'error',
  },
  { inputs: [], name: 'CollateralRegistry__InvalidPayment', type: 'error' },
  {
    inputs: [
      {
        internalType: 'enum CollateralRegistry.State',
        name: 'expected',
        type: 'uint8',
      },
      {
        internalType: 'enum CollateralRegistry.State',
        name: 'actual',
        type: 'uint8',
      },
    ],
    name: 'CollateralRegistry__InvalidState',
    type: 'error',
  },
  {
    inputs: [],
    name: 'CollateralRegistry__InvalidStateForDefault',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'address', name: 'expected', type: 'address' },
      { internalType: 'address', name: 'actual', type: 'address' },
    ],
    name: 'CollateralRegistry__InvalidUser',
    type: 'error',
  },
  { inputs: [], name: 'CollateralRegistry__LenderStillHasTime', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__NftNotInEscrow', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__NotAuthorized', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__NotOwner', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__PaymentFailed', type: 'error' },
  { inputs: [], name: 'CollateralRegistry__RentalNotEnded', type: 'error' },
  {
    inputs: [],
    name: 'CollateralRegistry__RenterMustNotBeLender',
    type: 'error',
  },
  { inputs: [], name: 'CollateralRegistry__RenterStillHasTime', type: 'error' },
  {
    inputs: [],
    name: 'CollateralRegistry__ReturnDeadlineMissed',
    type: 'error',
  },
  { inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'factory',
        type: 'address',
      },
    ],
    name: 'AuthorizationSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'lender',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'CollateralClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'nftContract',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
    ],
    name: 'NftDepositedByLender',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
    ],
    name: 'NftReleasedToRenter',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'renter',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'lender',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
    ],
    name: 'NftReturnedByRenter',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'lender',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'platform',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'lenderPayout',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'platformFee',
        type: 'uint256',
      },
    ],
    name: 'PayoutsDistributed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'renter',
        type: 'address',
      },
    ],
    name: 'RentalInitiated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'endTime',
        type: 'uint256',
      },
    ],
    name: 'RentalStarted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'enum CollateralRegistry.State',
        name: 'oldState',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'enum CollateralRegistry.State',
        name: 'newState',
        type: 'uint8',
      },
    ],
    name: 'StateChanged',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: '_factoryAddress', type: 'address' },
    ],
    name: 'addAuthorized',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'cancelRentalAfterClaimTimeout',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'claimCollateralWhenDefaulted',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'claimNFTWhenRenterUnableToClaim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_rentalId', type: 'uint256' },
      { internalType: 'address', name: '_lender', type: 'address' },
      { internalType: 'address', name: '_nftContract', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'uint256', name: '_hourlyRentalFee', type: 'uint256' },
      { internalType: 'uint256', name: '_collateral', type: 'uint256' },
      {
        internalType: 'uint256',
        name: '_rentalDurationInHours',
        type: 'uint256',
      },
      {
        internalType: 'enum RentalEnums.NftStandard',
        name: '_nftStandard',
        type: 'uint8',
      },
      {
        internalType: 'enum RentalEnums.DealDuration',
        name: '_dealDuration',
        type: 'uint8',
      },
    ],
    name: 'createRentalAgreement',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'depositNFTByLender',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'getTotalHourlyFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'getTotalRentalFeeWithCollateral',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'i_owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'initiateRental',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC1155BatchReceived',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC1155Received',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC721Received',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'reclaimFundsOnLenderTimeout',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'releaseNFTToRenter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'releaseNFTToRenterFromLender',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_factoryAddress', type: 'address' },
    ],
    name: 'removeAuthorized',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'returnNFTToLender',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 's_agreements',
    outputs: [
      { internalType: 'address', name: 'lender', type: 'address' },
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'uint256', name: 'hourlyRentalFee', type: 'uint256' },
      { internalType: 'uint256', name: 'collateral', type: 'uint256' },
      {
        internalType: 'uint256',
        name: 'rentalDurationInHours',
        type: 'uint256',
      },
      {
        internalType: 'enum RentalEnums.NftStandard',
        name: 'nftStandard',
        type: 'uint8',
      },
      {
        internalType: 'enum RentalEnums.DealDuration',
        name: 'dealDuration',
        type: 'uint8',
      },
      { internalType: 'address', name: 'renter', type: 'address' },
      {
        internalType: 'enum CollateralRegistry.State',
        name: 'rentalState',
        type: 'uint8',
      },
      { internalType: 'uint256', name: 'rentalEndTime', type: 'uint256' },
      {
        internalType: 'uint256',
        name: 'lenderDepositDeadline',
        type: 'uint256',
      },
      { internalType: 'uint256', name: 'returnDeadline', type: 'uint256' },
      { internalType: 'uint256', name: 'renterClaimDeadline', type: 'uint256' },
      { internalType: 'uint256', name: 'platformFeeBps', type: 'uint256' },
      { internalType: 'address', name: 'factoryAddress', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 's_isAuthorized',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
];
