services:
  lendr-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Add your environment variables here
      # - RPC_URL_AMOY=your_rpc_url
      # - RELAYER_PRIVATE_KEY=your_private_key
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - lendr-network

  # Optional: Add a reverse proxy (nginx)
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./ssl:/etc/nginx/ssl:ro  # Uncomment if using SSL
    depends_on:
      - lendr-api
    restart: unless-stopped
    networks:
      - lendr-network

networks:
  lendr-network:
    driver: bridge
# Optional: Add volumes for persistent data
# volumes:
#   app-data:
