services:
  lendr-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run start:dev
    restart: unless-stopped
    networks:
      - lendr-dev-network

networks:
  lendr-dev-network:
    driver: bridge
