export const DELEGATION_REGISTRY_ADDRESS =
  '0x6F7FF4977DA0253AcEEFf5389a86f8f67F371E4E' as const;

export const DELEGATION_REGISTRY_ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [], name: 'DelegationRegistry__ActiveDelegation', type: 'error' },
  {
    inputs: [],
    name: 'DelegationRegistry__AgreementDoesNotExist',
    type: 'error',
  },
  { inputs: [], name: 'DelegationRegistry__DeadlinePassed', type: 'error' },
  {
    inputs: [],
    name: 'DelegationRegistry__DelegationDeadlineNotPassed',
    type: 'error',
  },
  {
    inputs: [],
    name: 'DelegationRegistry__DelegationRentalDoesNotSupportNFTType',
    type: 'error',
  },
  {
    inputs: [],
    name: 'DelegationRegistry__DurationCannotBeZero',
    type: 'error',
  },
  { inputs: [], name: 'DelegationRegistry__InvalidAmount', type: 'error' },
  {
    inputs: [],
    name: 'DelegationRegistry__InvalidDealDuration',
    type: 'error',
  },
  { inputs: [], name: 'DelegationRegistry__InvalidNftContract', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__InvalidPayment', type: 'error' },
  {
    inputs: [
      {
        internalType: 'enum DelegationRegistry.State',
        name: 'expected',
        type: 'uint8',
      },
      {
        internalType: 'enum DelegationRegistry.State',
        name: 'actual',
        type: 'uint8',
      },
    ],
    name: 'DelegationRegistry__InvalidState',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'address', name: 'expected', type: 'address' },
      { internalType: 'address', name: 'actual', type: 'address' },
    ],
    name: 'DelegationRegistry__InvalidUser',
    type: 'error',
  },
  { inputs: [], name: 'DelegationRegistry__NftNotDeposited', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__NoBreachDetected', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__NotAuthorized', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__NotOriginalOwner', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__NotOwner', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__PaymentFailed', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__RentalIsOver', type: 'error' },
  { inputs: [], name: 'DelegationRegistry__RentalNotOver', type: 'error' },
  {
    inputs: [],
    name: 'DelegationRegistry__RenterMustNotBeLender',
    type: 'error',
  },
  { inputs: [], name: 'DelegationRegistry__WithdrawalFailed', type: 'error' },
  { inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'removedAuthorizedAddress',
        type: 'address',
      },
    ],
    name: 'AuthorizationRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'newAuthorizedAddress',
        type: 'address',
      },
    ],
    name: 'AuthorizationSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'nftContract',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
    ],
    name: 'DelegationRevoked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'nftContract',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'expires',
        type: 'uint64',
      },
    ],
    name: 'DelegationSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'nftContract',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
    ],
    name: 'NftDeposited',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'nftContract',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
    ],
    name: 'NftDepositedByLender',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'nftContract',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
    ],
    name: 'NftWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'lender',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'platform',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'lenderPayout',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'platformFee',
        type: 'uint256',
      },
    ],
    name: 'PayoutsDistributed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'renter',
        type: 'address',
      },
    ],
    name: 'RentalInitiated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'endTime',
        type: 'uint256',
      },
    ],
    name: 'RentalStarted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'rentalId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'enum DelegationRegistry.State',
        name: 'oldState',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'enum DelegationRegistry.State',
        name: 'newState',
        type: 'uint8',
      },
    ],
    name: 'StateChanged',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'activateDelegation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_factoryAddress', type: 'address' },
    ],
    name: 'addAuthorized',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'cancelDelegationRental',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'completeDelegationRental',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'rentalId', type: 'uint256' },
      { internalType: 'address', name: '_lender', type: 'address' },
      { internalType: 'address', name: '_nftContract', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'uint256', name: '_hourlyRentalFee', type: 'uint256' },
      {
        internalType: 'uint256',
        name: '_rentalDurationInHours',
        type: 'uint256',
      },
      {
        internalType: 'enum RentalEnums.NftStandard',
        name: '_nftStandard',
        type: 'uint8',
      },
      {
        internalType: 'enum RentalEnums.DealDuration',
        name: '_dealDuration',
        type: 'uint8',
      },
    ],
    name: 'createRentalAgreement',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_rentalId', type: 'uint256' }],
    name: 'depositNFTByLender',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'contractAddress', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'depositNFTtoEscrow',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'getDelegation',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'uint64', name: 'expires', type: 'uint64' },
        ],
        internalType: 'struct DelegationRegistry.Delegation',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'getRentalAgreement',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'lender', type: 'address' },
          { internalType: 'address', name: 'nftContract', type: 'address' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'hourlyRentalFee', type: 'uint256' },
          {
            internalType: 'uint256',
            name: 'rentalDurationInHours',
            type: 'uint256',
          },
          {
            internalType: 'enum RentalEnums.NftStandard',
            name: 's_nftStandard',
            type: 'uint8',
          },
          {
            internalType: 'enum RentalEnums.DealDuration',
            name: 'dealDuration',
            type: 'uint8',
          },
          { internalType: 'address', name: 'renter', type: 'address' },
          {
            internalType: 'enum DelegationRegistry.State',
            name: 'rentalState',
            type: 'uint8',
          },
          { internalType: 'uint256', name: 'rentalEndTime', type: 'uint256' },
          {
            internalType: 'uint256',
            name: 'lenderDelegationDeadline',
            type: 'uint256',
          },
          { internalType: 'uint256', name: 'platformFeeBps', type: 'uint256' },
          { internalType: 'address', name: 'factoryAddress', type: 'address' },
        ],
        internalType: 'struct DelegationRegistry.RentalAgreement',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'getTotalHourlyFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'i_owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'initiateDelegationRental',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC1155BatchReceived',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC1155Received',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'bytes', name: '', type: 'bytes' },
    ],
    name: 'onERC721Received',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'originalOwnerOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_factoryAddress', type: 'address' },
    ],
    name: 'removeAuthorized',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'rentalId', type: 'uint256' }],
    name: 'reportBreach',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'revokeDelegation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 's_isAuthorized',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 's_nftStandard',
    outputs: [
      { internalType: 'enum RentalEnums.NftStandard', name: '', type: 'uint8' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 's_rentalAgreements',
    outputs: [
      { internalType: 'address', name: 'lender', type: 'address' },
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'uint256', name: 'hourlyRentalFee', type: 'uint256' },
      {
        internalType: 'uint256',
        name: 'rentalDurationInHours',
        type: 'uint256',
      },
      {
        internalType: 'enum RentalEnums.NftStandard',
        name: 's_nftStandard',
        type: 'uint8',
      },
      {
        internalType: 'enum RentalEnums.DealDuration',
        name: 'dealDuration',
        type: 'uint8',
      },
      { internalType: 'address', name: 'renter', type: 'address' },
      {
        internalType: 'enum DelegationRegistry.State',
        name: 'rentalState',
        type: 'uint8',
      },
      { internalType: 'uint256', name: 'rentalEndTime', type: 'uint256' },
      {
        internalType: 'uint256',
        name: 'lenderDelegationDeadline',
        type: 'uint256',
      },
      { internalType: 'uint256', name: 'platformFeeBps', type: 'uint256' },
      { internalType: 'address', name: 'factoryAddress', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint64', name: 'expires', type: 'uint64' },
    ],
    name: 'setDelegation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'userExpires',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'userOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'nftContract', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'withdrawNft',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
